export const GET_REQUEST = 'GET_REQUEST';
export const GET_SUCCESS = 'GET_SUCCESS';
export const GET_ERROR = 'GET_ERROR';

export const POST_REQUEST = 'POST_REQUEST';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_ERROR = 'POST_ERROR';

export const PUT_REQUEST = 'PUT_REQUEST';
export const PUT_SUCCESS = 'PUT_SUCCESS';
export const PUT_ERROR = 'PUT_ERROR';

export const DELETE_REQUEST = 'DELETE_REQUEST';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_ERROR = 'DELETE_ERROR';

export const CHANGE_CREATE_FIELD = 'CHANGE_CREATE_FIELD';
export const CLEAR_CREATE_FIELDS = 'CLEAR_CREATE_FIELDS';
export const APPEND_CREATE_FIELD = 'APPEND_CREATE_FIELD';
export const REMOVE_CREATE_FIELD = 'REMOVE_CREATE_FIELD';

export const CHANGE_UPDATE_FIELD = 'CHANGE_UPDATE_FIELD';
export const CLEAR_UPDATE_FIELDS = 'CLEAR_UPDATE_FIELDS';
export const APPEND_UPDATE_FIELD = 'APPEND_UPDATE_FIELD';
export const REMOVE_UPDATE_FIELD = 'REMOVE_UPDATE_FIELD';
